apiVersion: v1
kind: Secret
metadata:
  name: vulnerable-postgres-db-secret
type: Opaque
data:
  password: cG9zdGdyZXM=
  user: cG9zdGdyZXM=

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: vulnerable-postgres-db-cm
data:
  init.sql: |
    CREATE DATABASE vulnerablenode;
    GRANT ALL PRIVILEGES ON DATABASE vulnerablenode TO postgres;

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-postgres-db-deploy
spec:
  selector:
    matchLabels:
      app: vulnerable-postgres-db
  template:
    metadata:
      labels:
        app: vulnerable-postgres-db
    spec:
      containers:
      - name: vulnerable-postgres-db
        image: postgres:12.7-alpine
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: vulnerable-postgres-db-secret
                key: user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: vulnerable-postgres-db-secret
                key: password
        volumeMounts:
          - name: postgres-initdb
            mountPath: /docker-entrypoint-initdb.d
          - mountPath: /var/lib/postgresql/data
            name: db-data
        resources:
          limits:
            cpu: 150m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 80Mi               
        ports:
        - containerPort: 5432
      volumes:
      - name: postgres-initdb
        configMap:
          name: vulnerable-postgres-db-cm 
      - name: db-data
        emptyDir: {}     
--- 
apiVersion: v1
kind: Service
metadata:
  name: vulnerabledb
spec:
  selector:
    app: vulnerable-postgres-db
  type: ClusterIP 
  ports:
  - port: 5434
    targetPort: 5432
