version: '3.9'
services:
  vulnerable_node:
    restart: always
    image: roxsross12/eko-vulnerable
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    restart: always
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./services/postgresql/ini.sql:/docker-entrypoint-initdb.d/ini.sql
