version: '3.9'
services:
  vulnerable_node:
    restart: always
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    restart: always
    build: ./services/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
