apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-app-deploy
spec:
  selector:
    matchLabels:
      app: vulnerable-app
  template:
    metadata:
      labels:
        app: vulnerable-app
    spec:
      containers:
      - name: vulnerable-app
        image: roxsross12/eko-devsecops:latest
        env:
          - name: STAGE
            value: DOCKER
        resources:
          limits:
            cpu: 150m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 80Mi
        ports:
        - containerPort: 3000

--- 
apiVersion: v1
kind: Service
metadata:
  name: vulnerable-app-svc
spec:
  selector:
    app: vulnerable-app
  type: NodePort  
  ports:
  - port: 3000
    targetPort: 3000
