name: Eko security pipeline

on:
    push:
        branches:
            - master

jobs:
    secret:
        name: secret-gitleaks-scan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: scan gitleaks
              run: docker run --rm -v $(pwd):/pwd zricethezav/gitleaks:latest detect --verbose --source="/pwd" --report-format=sarif --report-path=/pwd/gitleaks.sarif --log-level=debug 
              continue-on-error: true 
            - name: upload codeql
              uses: github/codeql-action/upload-sarif@v3
              with:
                sarif_file: gitleaks.sarif
                category: gitleaks
            
