name: Eko security pipeline

on:
    push:
        branches:
            - master

jobs:
    secret:
        name: secret-gitleaks-scan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: scan gitleaks
              run: docker run --rm -v $(pwd):/pwd zricethezav/gitleaks:latest detect --verbose --source="/pwd" --report-format=json --report-path=/pwd/gitleaks.json --log-level=debug  

