name: Eko security pipeline

on:
    push:
        branches:
            - master

permissions:
    security-events: write
    actions: read
    contents: read
    checks: write
    pull-requests: write

jobs:
    secret:
        name: secret-gitleaks-scan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: scan gitleaks
              run: docker run --rm -v $(pwd):/pwd zricethezav/gitleaks:latest detect --verbose --source="/pwd" --report-format=sarif --report-path=/pwd/gitleaks.sarif --log-level=debug 
              continue-on-error: true 
            - uses: actions/setup-python@v5
              with:
                python-version: '3.13' 
            - run: | 
                mv gitleaks.sarif /tmp/gitleaks.sarif
                cat /tmp/gitleaks.sarif
                python ./github/scripts/remove.py /tmp/gitleaks.sarif 
                mv /tmp/gitleaks.sarif gitleaks.sarif              
            - name: upload codeql
              uses: github/codeql-action/upload-sarif@v3
              with:
                sarif_file: gitleaks.sarif
                category: gitleaks
              continue-on-error: true 
    trivy:
        name: trivy scan
        needs: secret
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Build an image from Dockerfile
          run: docker build -t docker.io/roxsross12/my-app:${{ github.sha }} .
        - name: Run Trivy vulnerability scanner
          uses: aquasecurity/trivy-action@0.28.0
          with:
            image-ref: 'docker.io/roxsross12/my-app:${{ github.sha }}'
            format: 'table'
            exit-code: '1'
            ignore-unfixed: true
            vuln-type: 'os,library'
            severity: 'CRITICAL,HIGH'
          continue-on-error: true 